name: ci
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install bats
        shell: bash
        run: |
           sudo apt-get update
           sudo apt-get install bats
      - name: Run a one-line script
        run: make test

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: install golang
        shell: bash
        run: brew install go
      - name: Run a one-line script
        shell: bash
        run: make validate
      - name: Run ci
        shell: bash
        run: make ci

